# Generated by Django 5.1.6 on 2025-06-07 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwofu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('description', models.TextField()),
                ('hero_image', models.ImageField(upload_to='projects/')),
                ('date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('philosophy', models.TextField(blank=True)),
                ('testimonial', models.TextField(blank=True, null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
