# Generated by Django 5.1.6 on 2025-06-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inwofu', '0002_project'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='client_name',
        ),
        migrations.RemoveField(
            model_name='project',
            name='date',
        ),
        migrations.RemoveField(
            model_name='project',
            name='hero_image',
        ),
        migrations.RemoveField(
            model_name='project',
            name='location',
        ),
        migrations.RemoveField(
            model_name='project',
            name='philosophy',
        ),
        migrations.RemoveField(
            model_name='project',
            name='testimonial',
        ),
        migrations.RemoveField(
            model_name='project',
            name='type',
        ),
        migrations.AddField(
            model_name='project',
            name='date_created',
            field=models.DateField(default='2024-01-01'),
        ),
        migrations.AlterField(
            model_name='project',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='projects/')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inwofu.project')),
            ],
        ),
    ]
